sudo: required
cache:
  packages: true
  apt: true
  directories:
    - $HOME/.ya

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libc6-dev
      - python-dev
      - python3-dev

before_script: |
    # `ya` provides it's own compiler toolchains, `CC` and CXX` environment variables will override
    # them so we have to unset them.
    #
    unset CC
    unset CXX
    pip install webdavclient || sudo pip2 install webdavclient

matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: 3.6
      env: CB_BUILD_AGENT='python36-linux-x86_64-release'
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh
    - os: linux
      group: edge
      dist: focal
      virt: vm
      arch: arm64-graviton2
      language: python
      python: 3.6
      env: CB_BUILD_AGENT='python36-linux-aarch64-release'
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh 
